### ISSUE TITLE
PSGSetMusicVolumeAttenuation  seems not to be working

### ISSUE THREAD

**Issue by kusfo** [sverx/devkitSMS#13]
I'm trying to implement a fade-in , fade-out with the music, but it looks like the PSGSetMusicVolumeAttenuation  is not working properly. Setting it to any value (from 0 to 15) makes the music be reduced a some static cracks. Has anyone tried to perform such a fade effect?

**Comment by SteveProXNA** [comment]
Hi Kusfo - I a similar experience when I tried to fade out some music once.  I asked sverx if maybe I was doing something wrong... in the end I just left this idea out and not been able to implement fade out in any projects... it would be cool to get this working though esp. fade in music on a splash screen for instance.

**Comment by kusfo** [comment]
Mmmm, so maybe I'll need to take a look at the implementation and see if something is wrong.

**Comment by sverx** [comment]
I'll look into this ASAP

**Comment by sverx** [comment]
I'm trying with this simple test program and it sounds like it's working properly.
I'll wait for your feedback, guys.

```
#include "../SMSlib/SMSlib.h"
#include "../PSGlib/PSGlib.h"
#include "assets2banks.h"

unsigned int kp;
unsigned char att=0;

void main (void) {
  PSGPlay(tune_psg);

  for (;;) {
    SMS_waitForVBlank();
    PSGFrame();

    kp=SMS_getKeysPressed();

    if (kp & PORT_A_KEY_DOWN) {
      if (att<15) {
        PSGSetMusicVolumeAttenuation(++att);
      }
    } else if (kp & PORT_A_KEY_UP) {
      if (att>0) {
        PSGSetMusicVolumeAttenuation(--att);
      }
    }
  }
}
```

**Comment by SteveProXNA** [comment]
Thanks sverx - I have tried code like this on my existing music file but unfortunately the music still plays static cracks or not at all once the attenuation API is applied.  I have tried with the latest version of the PSGlib so I think it *may* depend on the music file you use??  One other thing that I noticed is that you are using asset2banks whereas I still use folder2c [sigh] but I don't think that should make any difference to how the bytes are produced for the final binary and how the music would be played with the attenuation set accordingly.

**Comment by sverx** [comment]
Did you try with exactly this code?
Alternatively, by chance are you calling PSGSetMusicVolumeAttenuation() function every frame in your code?

**Comment by sverx** [comment]
Found the bug.
https://github.com/sverx/devkitSMS/commit/068365d72d40b09f39ad3793800b04d14ce9118a
Please update.

**Comment by SteveProXNA** [comment]
Hi sverx - thanks for this!  FYI: I actually replicated your code sample with an old version of the PSGlib binary and the music volume would increase / decrease OK but the sound was "choppy".  However, after replacing with the latest binary the music attenuation is smooth - real smooth.  In fact, if you call the attenuation API each frame then music volume also remains smooth.  Great job!
