### ISSUE TITLE
Can't find sdcc 3.9.5

### ISSUE THREAD

**Issue by alekmaul** [sverx/devkitSMS#14]
Hello,
In readme, you"re talking about sdcc 3.9.5, but I can only find 3.9.0 version here : http://sdcc.sourceforge.net/ or https://sourceforge.net/projects/sdcc/files/
Where can I find sdcc 3.9.5 ?

**Comment by sverx** [comment]
The 3.9.5 requirement is the minimum requirement to compile the library.
For development please use any recent SDCC snapshot.
Note that SDCC 4 introduced a few changes so if you need to re-compile the library yourself, you need to modify it a bit.
I'm working on it.

**Comment by alekmaul** [comment]
Hi sverx,
it seems that the recent SDCC snapshots are only with 4.0 versions :/
I will wait for your new version of the lib compatible with SDCC 4.
I found this day someone in France who have the 3.9.5 version, so I can now continue to try your lib with the correct SDCC toolchain.

**Comment by sverx** [comment]
I didn't mean to say that the library isn't compatible with SDCC 4.x, it's just that the library sources wouldn't compile perfectly.
In short: it's totally fine to use the _current library_ with SDCC 4.x if you're not going to recompile the library yourself.
I hope this is clearer.

**Comment by alekmaul** [comment]
yep, for sure. As I found another way to find sdcc 3.9.5, we can close this issue.
