### ISSUE TITLE
Can I use the makesms to convert the file that contains CODE and DATA bank

### ISSUE THREAD

**Issue by 110-kenichi** [sverx/devkitSMS#18]
Can I use the makesms to convert the file that contains CODE and DATA bank?

func1.c～～～～～～
#pragma codeseg CODEBANK1
func1() __banked
～～～～～～

func2.c～～～～～～
#pragma codeseg CODEBANK2
func2() __banked
～～～～～～

data2.c～～～～～～
#pragma constseg DATABANK2
data2()
～～～～～～

data3.c～～～～～～
#pragma constseg DATABANK3
data3()
～～～～～～

#>sdcc -o file.ihx -mz80 --no-std-crt0 --data-loc 0xC000 -Wl-b_CODEBANK1=0x14000 -Wl-b_CODEBANK2=0x24000 -Wl-b_DATABANK2=0x8000 -Wl-b_DATABANK3=0x8000 crt0b_sms.rel SMSlib.lib main.rel fun1.rel func2.rel data2.rel data3.rel 
#> makesms file.ihx file.sms

-> It won't run properly...?

**Comment by sverx** [comment]
I'm not sure what you want to get here, I wouldn't use both CODEBANK2 and DATABANK2...

anyway the main problem I see here is the linking: you need to specify virtual addresses for the data banks too so it's

` -Wl-b_DATABANK2=0x38000 -Wl-b_DATABANK3=0x48000 `

and you can see why I would use DATABANK3 and DATABANK4 instead.

... oh, wait, unless you want to use bank 2 for BOTH code and data because why not? So you need correct virtual addresses anyway:

` -Wl-b_DATABANK2=0x28000 -Wl-b_DATABANK3=0x38000 `

**Comment by 110-kenichi** [comment]
Ah... Thanks!
I want to use both code and data banks.

I will try to use this "-Wl-b_DATABANK2=0x28000 -Wl-b_DATABANK3=0x38000"

**Comment by 110-kenichi** [comment]
Hmm.... I could not locate data banks properly...

Could you please tell me the proper way to use both data and code banks ? 
I think makesms does not support data bank like ihx2sms does...

**Comment by sverx** [comment]
first: `ihx2sms` doesn't support banked code, so you can't use that tool and you have to rely on `makesms` instead, which supports banked data _and_ code and uses virtual addresses

the easiest way to have banked code and banked data in your program is to have whole banks contain either code or data, even if sometimes this requires a bit of waste

so if your banked code uses, for instance, 3 banks, you may want to call them BANK1, BANK2 and BANK3

then your banked data will start from BANK4, say you also have BANK5 and BANK6

then you will link those banks using:

`-Wl-b_CODEBANK1=0x14000 -Wl-b_CODEBANK2=0x24000 -Wl-b_CODEBANK3=0x34000 -Wl-b_DATABANK4=0x48000 -Wl-b_DATABANK5=0x58000 -Wl-b_DATABANK6=0x68000`

that is: _code_ banks will be at address `x4000` and _data_ banks at address `x8000` (please note that this is hexadecimal so DATABANK10 will be at `A8000` not at `108000`)

I hope this helps!

**Comment by 110-kenichi** [comment]
mmm. Gave up.
Why the makesms places 2nd code bank to 8000H in sms file? I think 8000H is data bank.
//1st code bank is placed to 4000H in sms file.

**Comment by sverx** [comment]
did you try something easy like:

```
sdcc -c -mz80 --codeseg BANK1 bank1.c
sdcc -c -mz80 --codeseg BANK2 bank2.c
sdcc -c -mz80 --codeseg BANK3 bank3.c
sdcc -c -mz80 --constseg BANK4 bank4.c
sdcc -c -mz80 --constseg BANK5 bank5.c
sdcc -o file.ihx -mz80 --no-std-crt0 --data-loc 0xC000 -Wl-b_BANK1=0x14000 -Wl-b_BANK2=0x24000 -Wl-b_BANK3=0x34000 -Wl-b_BANK4=0x48000 Wl-b_BANK5=0x58000 crt0b_sms.rel SMSlib.lib main.rel bank1.rel bank2.rel bank3.rel bank4.rel bank5.rel
```
this is what I do in my code and it works fine.

**Comment by 110-kenichi** [comment]
> did you try something easy like:

oops, i will try.

**Comment by sverx** [comment]
Also don't let the SMS ROM file fool you. The banks are ordered there but their address is in no way indicative of at what address the Z80 will see them. So code can be at ROM address 0x8000 (ROM bank 2) but will be mapped at Z80 address 0x4000 because that's what mappers do :smile:

**Comment by 110-kenichi** [comment]
When I use BANK4 data, which number should I specify to the SMS_mapROMBank( xxx ) API ?

**Comment by sverx** [comment]
4, of course.
If you use assets2banks tool, you get a bunch of defines that you can use and not even worry about what's the actual value.
Please check that. It's the fastest and easiest way to handle assets (data).

**Comment by sverx** [comment]
`assets2banks.py assets --firstbank=4 --compile --singleheader`

this will create your rel files directly, starting from bank4.rel, and will create the assets2banks.h file with all the defines you need

**Comment by 110-kenichi** [comment]
Bingo! Thank you!

I could run my program, but..... only when I removed "__banked" magic word from a function. Is that okay...?

So, I must write the following codes... ( SMS_mapCODEBank() is my custom API )

>            SMS_mapCODEBank(1);
>            SMS_mapROMBank(4);
>            functionBank1();  // Using BANK4 data
>
>            SMS_mapCODEBank(2);
>            SMS_mapROMBank(5);
>            functionBank2();   // Using BANK4 data

**Comment by sverx** [comment]
If everything is done correctly, code mapping should be transparent - you shouldn't need that.

If it wasn't working when the __banked keyword was present, it is likely because the declaration of the function was missing that part. What I mean is that you need to have a .h file that declares that function as banked and you have to include that .h file in your main, or if you don't want a separate .h file, you have to anyway declare the banked function in your main.c as in

`void functionBank1(void) __banked;`

**Comment by 110-kenichi** [comment]
Hmm... Failed... I placed "__banked" keyword to both declaration and function body... mmm...

**Comment by 110-kenichi** [comment]
And do you know what means the following compiler warning message ? Can I skip this message?

`source.c:17: info 218: z80instructionSize() failed to parse line node, assuming 999 bytes
'b_fuctionBank1  = 1'`

**Comment by 110-kenichi** [comment]
Hmm...  Can I use bank number 5 or above ? I can not run my program that is using bank number from 1 to 6....

**Comment by sverx** [comment]
you can ignore that SDCC message, it's a leftover debug info, I have a few of them too and still everything works

**Comment by sverx** [comment]
please try with something very simple like [this example here](https://www.smspower.org/forums/18183-DevkitSMSExperimentalBranch#112939), you'll see the basics of transparent code banking at work

**Comment by 110-kenichi** [comment]
Thank you so much!

My demo program is here.
https://twitter.com/SNDR_SNDL/status/1381956874287808520

**Comment by sverx** [comment]
You might want to use that or you might place the regular header on the source code that goes to bank 1 - I would use that _16KB as it's just easier.

**Comment by 110-kenichi** [comment]
So sorry.
SMS_mapCODEBank() is deprecated on recent version ?

**Comment by sverx** [comment]
I never added `SMS_mapCODEBank()` in the first place, as that wasn't needed at all.

If you use transparent code banking you don't need to do anything beside declaring the banked code as banked.

**Comment by 110-kenichi** [comment]
Oops.. so sorry. It is my fault...
