### ISSUE TITLE
32bits variables

### ISSUE THREAD

**Issue by Alirio926** [sverx/devkitSMS#21]
It's not a problem, but is there a way to make calculations with 32-bit variables?

tried:

> unsigned long ab = 0x10001;
char buffer[24];
sprintf(buffer, "%d", sizeof(ab));
draw_text(buffer, 9, 2);
sprintf(buffer, "%d", ab);
draw_text(buffer, 9, 3);

But this print:
4 and 1, so unsignd long is 32 bits but why cannot show?

drawText method.

> void draw_text(unsigned char* text, unsigned char x, unsigned char y)
{
    //const unsigned int* pnt = devkitSMS_font__tiles__1bpp;
    unsigned char idx = 0;
    while ('\0' != text[idx])
    {
        signed char tile = text[idx];// -TEXT_ROOT;
        SMS_setNextTileatXY(x++, y);
        SMS_setTile(SMS_TextRenderer_offset + tile);
        idx++;
    }
}

**Comment by sverx** [comment]
I suspect the problem might be in
`sprintf(buffer, "%d", ab);`

unsigned long are surely supported by the compiler (SDCC) but I never used their sprintf implementation, it might not work as expected

**Comment by Alirio926** [comment]
You're right, I changed the parameter to %lu and it worked, Thanks!!!
