### ISSUE TITLE
issue with compressed songs spawning multiple banks

### ISSUE THREAD

**Issue by sverx** [sverx/devkitSMS#48]
Hey @raphnet !

I had an heads up about a strange bug that happens only with compressed songs with the PSGLIB_MULTIBANK version of the PSGlib library.

I suspect the issue happens when the two-byte address of a substring ends up exactly at the end of the bank (`$BFFE`, `$BFFF`) - in this case the mapper still retains the 'old' bank number when you get to [this line](https://github.com/sverx/devkitSMS/blob/master/PSGlib/src/PSGlib.c#L512) so when the compressed block ends the music continues from the beginning of the bank that is the previous one instead of the one that should be, as you're saving $8000 in HL
`ld (_PSGMusicSubstringRetAddr),hl   ; save return address `
but you're NOT saving the incremented bank number...

Can you look into this? Thanks! :bow:

**Comment by raphnet** [comment]
Ah, I see... I think you are correct! You already did the hard work of finding the problem... Thank you!
_PSG_ReadByte_B/C saves the incremented bank in _PSGMusicPointerBank, so I should just read the bank from (_PSGMusicPointerBank) instead of f ($FFFF)

In other words, I suggest replacing this:
> ld a, (0xFFFF)
> ld (_PSGMusicSubstringRetBank),a    ; save return bank

By this:
> ld a, (_PSGMusicPointerBank)
> ld (_PSGMusicSubstringRetBank),a    ; save return bank

**Comment by sverx** [comment]
oh right, I didn't realize that! :man_facepalming:

**Comment by sverx** [comment]
Confirmed fixed. Closing this.
