### ISSUE TITLE
Library doesn't preserve IY register in SMSlib_PSGaiden.c

### ISSUE THREAD

**Issue by aralbrec** [sverx/devkitSMS#5]
Unless programs are compiled with the `--reserve-regs-iy` flag, SDCC expects the IY register to be preserved across calls just like IX.

In [SMSlib_PSGaiden.c](https://github.com/sverx/devkitSMS/blob/master/SMSlib/src/SMSlib_PSGaiden.c), IY is used but is not saved.  IX is saved.

**Comment by sverx** [comment]
According to the SDCC manual, if I got the meaning correctly, it should be the other way around.
As we're not using the `--preserve-regs-iy` flag, IY can be used as a temporary register, as written in section 4.3 of the manual:

> Register A, B, C, D, E, H, L and IY are used as a temporary registers for holding variables.

**Comment by aralbrec** [comment]
I mistyped there - in the above I meant the `--reserve-regs-iy` flag which I have corrected in the original post.

Despite what the manual says, I have come across instances where sdcc has used an old IY value across a function call that did not indicate IY was preserved.  I tried some test compiles tonight to try to find an example without success but I will continue to try a few more and see if I can find an example.

**Comment by sverx** [comment]
If you find that some generated code is assuming that IY is unchanged after a call, then it might be an SDCC error - or you might have called a function that has a `__preserves_regs( )` declaration attached to it.
In either case please let me know. I'm leaving this open for your feedback :)

(I also edited my last post to fix that `--reserve-regs-iy`)

**Comment by sverx** [comment]
closing this
