### ISSUE TITLE
crt0_sg.s incorrect initialization of I/O chip

### ISSUE THREAD

**Issue by JoppyFurr** [sverx/devkitSMS#58]
Hi,

I noticed when testing my code on an SC-3000H, that gamepad input was not working correctly.
Instead of taking input from my gamepad, the input was coming from a handful of keyboard keys.

It looks like the cause is that in crt0_sg.s, the I/O chip control register is being initialized with 0x9f when it should be initialized with 0x92.
```
  ld a,#0x9F
  out (0xDF),a      ; Config PPI (no effect on SG-1000)
```

Cheers,
Joppy

**Comment by sverx** [comment]
Thank you! :heart:
