### ISSUE TITLE
SC-3000 Cassette Support

### ISSUE THREAD

**Issue by JoppyFurr** [sverx/devkitSMS#59]
Hi,

I'm not sure where else to put this, but I've been playing with loading SGlib programs from tape and have now got interrupts working. I thought I'd post a copy of my modified `crt0_sg.s` here in case you wanted to make use of it.

The `LOAD` command from basic puts things at `0x9800`
It is jumped to using `CALL &H9800` from BASIC.

For memory layout, I use:
 * `0x8000` as the start of work-ram, for 5.5 KiB
 * `0x9600` as the interrupt vector table (using interrupt-mode 2)
 * `0x9800` is the start of loaded code, where the first line of crt0 gets placed
 * `0x9898` is the interrupt vector
 * `0x98a0` is the `code-loc` that I pass to the linker, although I'm not sure if this is needed. The intention was to prevent user-code from clobbering anything in crt0.

If counting from 0x9800, the program can reach 12 KiB on a BASIC IIIa cartridge, or 26 KiB on a BASIC IIIb cartridge.

Cheers,
Joppy

```assembly
;--------------------------------------------------------------------------
; *** this is a modified version aimed to SG-1000 homebrew - sverx\2015 ***
; *** additional changes aimed at SC-3000 tape homebrew - JoppyFurr\2024 ***
;--------------------------------------------------------------------------
;--------------------------------------------------------------------------
;  crt0.s - Generic crt0.s for a Z80
;
;  Copyright (C) 2000, Michael Hope
;
;  This library is free software; you can redistribute it and/or modify it
;  under the terms of the GNU General Public License as published by the
;  Free Software Foundation; either version 2, or (at your option) any
;  later version.
;
;  This library is distributed in the hope that it will be useful,
;  but WITHOUT ANY WARRANTY; without even the implied warranty of
;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
;  GNU General Public License for more details.
;
;  You should have received a copy of the GNU General Public License
;  along with this library; see the file COPYING. If not, write to the
;  Free Software Foundation, 51 Franklin Street, Fifth Floor, Boston,
;   MA 02110-1301, USA.
;
;  As a special exception, if you link this library with other files,
;  some of which are compiled with SDCC, to produce an executable,
;  this library does not by itself cause the resulting executable to
;  be covered by the GNU General Public License. This exception does
;  not however invalidate any other reasons why the executable file
;   might be covered by the GNU General Public License.
;--------------------------------------------------------------------------


; SC-3000 Tape Changes:
;  - No interrupt handling, BASIC owns the vector addresses.
;  - Code begins at 0x9800
;    -> Has up to 0xc7ff for BASIC IIIa (12 KiB)
;    -> Has up to 0xffff for BASIC IIIb (26 KiB)
;  - RAM at 0x8000 -- 0x95ff (5.5 KiB) will be free once we take over from basic.
;  - Interrupt Vector table at 0x9600 -- 0x9700 (257 bytes)

  .module crt0
  .globl  _main
  .area _HEADER (ABS)
  .org 0x9800

start::
  di                ; disable interrupt
  ld sp,#0x95f0     ; set stack pointer at end of our 5.5k block of RAM
  xor a             ; clear RAM (to value 0x00)
  ld hl,#0x8000     ;   by setting value 0
  ld (hl),a         ;   to $c000 and
  ld de,#0x8001     ;   copying (LDIR) it to next byte
  ld bc,#0x1600-17  ;   for 5.5 KB minus 17 bytes
  ldir              ;   do that

  ;; ensure this runs fine on SC-3000 too
  ld a,#0x92
  out (0xDF),a      ; Config PPI (no effect on SG-1000)
  ld a,#7
  out (0xDE),a      ; Select ROW 7 (row 7 of PPI is joypad = default - no effect on SG-1000)

  ;; Set up for interrupt-mode 2
  ;; Register I controls the vector MSB. The vector LSB is whatever happens to be on the bus.
  ;; So, a 257-entry table with a single repeated byte (0x98) will give us a reliable 0x9898 call.
  im 2              ; interrupt mode 2 (this will not change)
  ld a,#0x96        ; Vector table at 0x9600, between work-ram and code.
  ld i,a

  ld a,#0x98
  ld hl,#0x9600
  ld (hl),a         ; Initialize first byte of vector table at 0x9600 to value 0x98
  ld de,#0x9601     ; Prepare copy to the next byte
  ld bc,#0x0100     ; Copy for 256 bytes, giving 257 bytes total.
  ldir

  ;; Initialise global variables
  call    gsinit
  call    _SG_init
  ei                ; re-enable interrupts before going to main()
  call  _main
  jp  _exit

  .org 0x9898       ; handle IRQ
  jp _SG_isr

  ;; Ordering of segments for the linker.
  .area _HOME
  .area _CODE
  .area _INITIALIZER
  .area   _GSINIT
  .area   _GSFINAL

  .area _DATA
  .area _INITIALIZED
  .area _BSEG
  .area   _BSS
  .area   _HEAP

  .area   _CODE
__clock::
  ld  a,#2
  rst     0x08
  ret

_exit::
  ;; Exit - special code to the emulator
  ld a,#0
  rst 0x08
1$:
  halt
  jr 1$

  .area   _GSINIT
gsinit::
  ld  bc, #l__INITIALIZER
  ld  a, b
  or  a, c
  jr  Z, gsinit_next
  ld  de, #s__INITIALIZED
  ld  hl, #s__INITIALIZER
  ldir
gsinit_next:

  .area   _GSFINAL
  ret
```

**Comment by sverx** [comment]
I wish I could understand what you're doing here.
Why do you need _interrupt mode 2_ for instance? :thinking:

**Comment by JoppyFurr** [comment]
The reason for interrupt-mode 2:

Most software that runs on 8-bit Sega hardware uses interrupt-mode 1.
In interrupt-mode 1, when an interrupt occurs, the CPU will run code at 0x0038.

Unfortunately, when running from tape, we have no control over what is at 0x0038, that address is part of the BASIC cartridge's ROM and cannot be changed. So instead, we need a way to have our interrupt handler be located in  RAM (addresses above 0x8000)

Interrupt-mode 2 allows this. The `I` register is used as the base-address of a 128-entry (128 16-bit pointers) vector table, where the entry is selected by whatever data-bit is on the bus (out of our control). If we create a table in RAM, where every index, included indexes half-way-between two entries, the same (eg, a single repeating byte), then whatever data is on the bus, the same interrupt handler address will be used.

It may be explained better here: https://www.smspower.org/Development/InterruptMechanism

The end result is: By creating a table full of repeating 0x98, and using the `I` register to point at that table, then whatever random data happens to be on the bus at the time, the address taken from the vector table will be 0x9898. An address that we can load code into from tape.

Hopefully this explains the reasoning

**Comment by sverx** [comment]
I understand now why you switched to `IM 2`.
I wonder why BASIC didn't provide any way to trigger custom code when an interrupt is received, such as `ON INTERRUPT GOSUB xxxx` or similar. :thinking: 

Anyway, I could add this as a `crt0_BASIC.s`, and have a note in the README explaining what's for. Does this makes sense?

Also, please send a pull request :smiley: 

Thanks!

**Comment by JoppyFurr** [comment]
I'll try got get something tidied up for submission at some point in the next few days.

I did have a question around the existing crt0 before submitting a pull request:

In your crt0_sg.s, I see a repeated block of 128 repeated `OUTI` instructions, with the label `_outi_block`. I see that `SMSlib` uses this in some of its `UNSAFE` functions. However, I don't see it ever being used by `SGlib`. My thought was, if there's no plan for `SGlib` to use the block, to leave it out. (seeing as space is more limited)

Is there any reason I should keep `_outi_block` that I'm not aware of?

**Comment by sverx** [comment]
PR #60 merged, so we can close this :smiley:
