### ISSUE TITLE
ihx2sms fails with multi-segment static libraries

### ISSUE THREAD

**Issue by wootguy** [sverx/devkitSMS#6]
When linking with a static library containing multiple code segments/banks, SDCC seems to arrange the segments in a random order (not in the order the lib sources were compiled and linked). This breaks ihx2sms because it assumes segment order == link order.

One way to solve this would be to have ihx2sms read the .map file which shows the order SDCC placed the segments in the .ihx file. Doing that would also eliminate the need to link objects in a specific order.

**Comment by sverx** [comment]
I'd like to see one of those libraries so to run a few test. Any hint?

**Comment by wootguy** [comment]
I tried to make a simple example but it only seems to be happening with my library. I've simplified it a bit and [uploaded here](http://w00tguy.no-ip.org/owncloud/index.php/s/Il93R0NqhdXkGri/download) (couldn't attach for some reason).

It's compiled for Gameboy since I haven't added support for SMS yet, and if you want to build it you'll need to change SDCC_ROOT in the batch file. To place banked code I use "#pragma bank X" (which assigns to _CODE_X) instead of "--constseg BANKX".

The important part is that despite the code being archived/linked in order (bank1, then bank2,  then bank3), the banks are placed differently in the final .ihx (in this case: bank3, then bank2, then bank1). It's not always reverse order, sometimes I'll get 2, 3, 1 depending on which code is banked.

To verify bank order I check the .map file and look at the order the code areas appear.

**Comment by sverx** [comment]
I gave a look at your code, and I think ihx2sms isn't the right tool for what you're trying to do.

For instance, you're banking code at 0x4000 and ihx2sms converter expects only "slot 2" banking (at 0x8000, that is) so your code at 0x4000 will be overwritten each time the next CODE_X block starts.
And beside all this, ihx2sms really relies on the order the data is written into the IHX file.

So I guess my suggestion is to fork from here and customize your own converter, or start from scratch, which might even be easier giving that ihx-to-bin conversion isn't very complicated.
As for the code blocks order problem, maybe parsing the .map file is the way to go... well, at least I don't have any better suggestion :|

I leave this open for your feedback :)

**Comment by wootguy** [comment]
I'm using 0x4000 as the switchable bank address for my own Gameboy bin converter, which is based on the clever idea behind ihx2sms. If I were compiling for SMS I would use 0x8000 since that's what the SDK expects.

Would you want a pull request if I modified ihx2sms to read .map files?

**Comment by sverx** [comment]
If I get it right, you mean to parse a map file to obtain the order of the banks (but not the addresses) in the ihx file input of ihx2sms?
If so, surely I'd like a pull request! :)

If I may ask, I'd like that to be an _optional_ command line switch parameter, specified before the actual input and output compulsory parameters as in
`ihx2sms [-m mapfile] input.ihx output.sms`
so that there are no changes needed for those who don't need such a peculiar feature.

**Comment by wootguy** [comment]
Yep, that's the idea. I'll make it optional as you said. 👌

**Comment by sverx** [comment]
Sorry for coming back to you so late!
I'll check your code in the next few days.
Thanks for your submission!

**Comment by wootguy** [comment]
Not a problem. Don't hesitate to ask for changes.

**Comment by sverx** [comment]
Thanks for the contribution, it's now merged.
