### ISSUE TITLE
assets2banks with files > 16kb in size

### ISSUE THREAD

**Issue by joffb** [sverx/devkitSMS#61]
Hello, 

Have been trying to use assets2banks with files larger than 16kb and even with --allowsplitting it didn't output any banks, and just gave the "Fatal: no banks generated" error

I had a play about with the python code and managed to get it working by making some changes at around line 480 where i set the part.size and apartgrp.size like this:

```
                    if a.size <= gf and offset == 0:
                        apartgrp.add_asset(a)
                    else:
                        part = Asset(a.name + "_PART" + str(partno), l)
                        part.data = a.data[offset:offset+l]
                        part.size = l
                        apartgrp.size += l
                        apartgrp.add_asset(part)

```
I think apartgrp.size needs to be set as it's is used in the `gf = 16384 - apartgrp.size` and `if apartgrp.size > 0:` in that section to actually add the assets to banks 

Have uploaded my modified version but I'm sure you'll know the proper way to do it!

Thanks,
Joe
[assets2banks.zip](https://github.com/sverx/devkitSMS/files/14925251/assets2banks.zip)

**Comment by sverx** [comment]
uhm, I'm pretty sure it was working so I must have broken something recently when I added a few more features. :thinking: 
Thanks for letting me know! I'll look into it ASAP - but I'm happy you found a workaround in the meantime.

**Comment by sverx** [comment]
I confirm I had broken the `--allowsplitting` feature while releasing assets2banks version 3.0.0 and for some reason I failed to see it.
Now it seems to be working as intended.
Thanks for your feedback! :heart:

**Comment by joffb** [comment]
Thanks sverx!

**Comment by sverx** [comment]
No worries! Please note that I have just pushed one more commit, as there was still an issue. :roll_eyes:
