### ISSUE TITLE
SMS_updateSpritePosition and SMS_updateSpriteImage

### ISSUE THREAD

**Issue by xfixium** [sverx/devkitSMS#66]
SMS_updateSpritePosition and SMS_updateSpriteImage don't seem to function anymore? As far as I can tell.

**Comment by sverx** [comment]
They should work, provided you are using the _sprite_id_ returned by `SMS_addSprite()` (compiled without `NO_SPRITE_CHECKS` defined) or by `SMS_reserveSprite()` ... :thinking:

**Comment by xfixium** [comment]
Aye, I believe that is it, the compile options. Sorry, I seem to be finding non-issues of late XD
