### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by maxoakland** [sverx/devkitSMS#67]
I went to the Github pages link but I got this page:
<img width="770" alt="image" src="https://github.com/user-attachments/assets/945be6dd-bcb9-4bd4-9c10-d85251b76a7a">

**Comment by sverx** [comment]
I'm not sure what you did to get there, but the URL in the address bar suggests that you might be confusing devkitSMS with GBStudio.

devkitSMS wiki is [here](https://github.com/sverx/devkitSMS/wiki)
