### ISSUE TITLE
devkitSMS adopted in z88dk

### ISSUE THREAD

**Issue by aralbrec** [sverx/devkitSMS#7]
Thank you sverx for writing such a great library for sms.  We like to collect shiny things in [z88dk](https://github.com/z88dk/z88dk) so devkitSMS has been incorporated into the new c library in z88dk for the sms.  What has not been implemented is anything associated with GG or SC1000 as we're not sure yet if those machines are better served by their own independent targets inside z88dk; if it's decided to keep them part of the sms target, those functions will be added too.  I chose not to go the fork route because keeping things compatible with sdcc was restricting too much what we could do.

I am sharing to let you know, first of all, but also because you are welcome to take anything back into the original project that you may find useful.  In particular we've rewritten the C bits in assembler and separated each function into individual files.  The assembler rewrite reduces size and allows more preserve_regs flags to be specified which can improve on code quality a small amount.  It also makes the library directly accessible to asm programmers.  The fine granularity allows the linker to pick out individual subroutines from the library which can reduce program size somewhat.

[SDCC-compatible headers](https://github.com/z88dk/z88dk/tree/master/include/_DEVELOPMENT/sdcc/arch/sms)
* You will see defines in terms of "__FOO".  Defines are kept in the implementation's namespace (beginning with double underscore) and then are selectively revealed into the user's namespace via header files.

[PSGlib source code](https://github.com/z88dk/z88dk/tree/master/libsrc/_DEVELOPMENT/arch/sms/PSGlib)
[SMSlib source code](https://github.com/z88dk/z88dk/tree/master/libsrc/_DEVELOPMENT/arch/sms/SMSlib)
* c/sdcc holds the c interface to the assembly functions
* z80 holds the assembly implementation

[How devkitSMS is configured inside z88dk](https://github.com/z88dk/z88dk/blob/master/libsrc/_DEVELOPMENT/target/sms/config_devkitSMS.m4)
* Lines 10-18 are meant to be user-configurable.  I'm not sure if modifying PNTADDRESS, SATADDRESS, CRAMADDRESS is all it takes to move these things around in VRAM?
* The ENABLE_MDPAD option is used to control whether the regular ISR or the MDPAD_ISR is active when the devkitSMS crt is used.
* Non-zero values for ISRST_SMSCRT0RSTXX will cause calls to the SMS_CRT0_RSTXX functions to be replaced with restarts.

[devkitSMS page zero code](https://github.com/z88dk/z88dk/blob/master/libsrc/_DEVELOPMENT/target/sms/sms_page_zero_devkitSMS.inc)
* Optional page zero code for crts that want to have devkitSMS automatically configured in compiles.

[devkitSMS crt](https://github.com/z88dk/z88dk/blob/master/libsrc/_DEVELOPMENT/target/sms/startup/sms_crt_8.asm.m4)
* Follows the page zero code above.

You can use devkitSMS with any crt but a devkitSMS-specific one is selected with "-startup=8" on compile lines.  What this will do is place the two RSTs and the MI / NMI isrs in the right places, like what is done with native devkitSMS's crt for sdcc.

For testing we are using some source from the smspower website:

[split-screen](https://github.com/z88dk/z88dk/tree/master/libsrc/_DEVELOPMENT/EXAMPLES/sms/split-screen)
Your split screen example.  The original bmp assets are not committed - only the processed form required by the compile.  I hope it's ok if we can use it in our examples directory?

These others we do not have permission to host so they are temporarily in a separate branch that will ultimately be deleted:
[Temporary Examples](https://github.com/z88dk/z88dk/tree/newclib/IncorporateDevkitSMS/libsrc/_DEVELOPMENT/EXAMPLES/sms)
(I'm also still working a bit in there so the readme.txt are a little curt)

The one main difference between devkitSMS and this adaptation is that the macros used to defined the SEGA/SDSC headers are turned into no-ops.  In z88dk, header information is specified via pragmas which you will find (optionally) defined in zpragma.inc files associated with the examples above.

Thanks again sverx; feel free to close any time.

**Comment by sverx** [comment]
Great! Sure I'll check how you did it and I'll take some 'back' :)

>  I'm not sure if modifying PNTADDRESS, SATADDRESS, CRAMADDRESS is all it takes to move these things around in VRAM?

You can't move CRAM, you can move PNT and SAT location in VRAM only by instructing VDP about their 'new' locations, which are to be chosen from a list of (rather limited) possible values.

**Comment by aralbrec** [comment]
> You can't move CRAM, you can move PNT and SAT location in VRAM only by instructing VDP about their 'new' locations, which are to be chosen from a list of (rather limited) possible values.

Cheers sverx.

What I've done is define some SMS-target variables that determine default locations for these things:

```
define(`__SMS_VRAM_SCREEN_MAP_ADDRESS',  0x3800)              # multiples of 0x0800 - affects devkitSMS
define(`__SMS_VRAM_SPRITE_ATTRIBUTE_TABLE_ADDRESS', 0x3f00)   # multiples of 0x0100 - affects devkitSMS
define(`__SMS_VRAM_CHARACTER_PATTERN_BASE_ADDRESS', 0x2000)   # 0x0000 or 0x2000
```

and then I define the devkitSMS constants in terms of those so that there is only one place where these things need to be changed:

```
define(`__SMSLIB_PNTADDRESS',  0x`'eval(__SMS_VRAM_SCREEN_MAP_ADDRESS + 0x4000,16))
define(`__SMSLIB_SATADDRESS',  0x`'eval(__SMS_VRAM_SPRITE_ATTRIBUTE_TABLE_ADDRESS + 0x4000,16))
define(`__SMSLIB_CRAMADDRESS', 0xc000)
```

For SMS_init() I change the 11-byte VDP initialization block to this:

```
__SMSlib_VDPReg_init:

   defb 0x04                   ; /* reg0: Mode 4 */
   defb 0x20                   ; /* reg1: display OFF - frame int (vblank) ON */
   defb ((__SMSLIB_PNTADDRESS & 0x3800) >> 10) + 0xf1  ; /* reg2: PNT at 0x3800 */
   defb 0xFF                   ; /* reg3: no effect (when in mode 4) */
   defb 0xFF                   ; /* reg4: no effect (when in mode 4) */
   defb ((__SMSLIB_SATADDRESS & 0x3f00) >> 7) + 0x81   ; /* reg5: SAT at 0x3F00 */
   defb ((__SMS_VRAM_CHARACTER_PATTERN_BASE_ADDRESS & 0x2000) >> 11) + 0xfb  ; /* reg6: Sprite tiles at 0x2000 */
   defb 0x00                   ; /* reg7: backdrop color (zero) */
   defb 0x00                   ; /* reg8: scroll X (zero) */
   defb 0x00                   ; /* reg9: scroll Y (zero) */
   defb 0xFF                   ; /* regA: line interrupt count (offscreen) */
```

and I think this makes the the screen map, sprite attribute table, and character patterns relocatable within devkitSMS.

However there is one thing I am not understanding:  you've set the character/sprite patterns base address to 0x2000 by default (reg6 = 0xff) but the tile data is always using VDP addresses in the lower 8k.  

For example, in SMS_loadTiles():

```
   ;; SMS_setAddr(0x4000|(tilefrom*32))
   
   add hl,hl
   add hl,hl
   add hl,hl
   add hl,hl
   add hl,hl
   set 6,h
   
	ld a,c
   INCLUDE "SMS_CRT0_RST08.inc"
	ld c,a
```

The VDP address is just the tilenumber * 32 which places it in the lower 8k.  This despite reg6 having been initialized with the character pattern table beginning at 0x2000, the upper 8k.

I tried changing the character pattern table address to 0x0000 via the methods above and there was no difference at all.

There is something I am not understanding here.  How is it that devkitSMS defines a character/sprite pattern table address of 0x2000 but its tile functions write character data into addresses less than 0x2000 and things still work?

The example program I am looking at is your split-screen example.  It begins with:

```
  SMS_VDPturnOnFeature(VDPFEATURE_LEFTCOLBLANK);
  loadAssets();

->

void loadAssets (void) {
  // load the tiles for both pictures
  SMS_loadPSGaidencompressedTiles (p1__tiles__psgcompr, 0);
  SMS_loadPSGaidencompressedTiles (p2__tiles__psgcompr, 224);
}
```

SMS_init() has been called by the crt setting the character pattern address to 0x2000.  Then SMS_loadPSGaidencompressedTiles() is loading tile graphics into addresses < 0x2000 because the tile numbers are < 256.

**Comment by aralbrec** [comment]
Problem solved; I had a misunderstanding of what the sprite pattern base address was doing.  Misnaming it character pattern base address was a bad idea.

**Comment by sverx** [comment]
Sorry for coming back to you so late... well, I'm happy to see you got it by yourself - yes, that VDP bit just sets which of either halves of VRAM will be used for sprites.
